remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: somerville-schools-traffic-safety
description: Ranking Somerville public schools by safety priority using 3 years of crash data and traffic volume analysis

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: Jupyter notebook
    link: ./02_analysis_viz_duplicate
  - name: Executive Summary
    link: ./03_exec_summary